# Generated by Django 2.1.7 on 2019-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('description', models.TextField()),
                ('additional_link', models.URLField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
