# Generated by Django 2.1.7 on 2019-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='additional_link',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='finish_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
